### ISSUE TITLE
Bug 8934 - Irregularity in stem() display 

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-day#12]
[Bug 8934](https://bugs.r-project.org/show_bug.cgi?id=8934) describes some long-standing issues with the `stem()` function for creating stem-and-leaf plots, the main one being that the divider between the stem and the leaf is not always aligned across rows.

The bulk of the code is in the underlying `stem_leaf` C function: https://github.com/r-devel/r-svn/blob/cd94cda92d838a2938cdb90b51ca1d0cc3eeb7af/src/library/graphics/src/stem.c#L51.

So fixing the alignment bug would require working through this code to understand how the alignment is determined and whether it can changed to make the dividers always line up.

**Comment by EllaKaye** [comment]
I'm interested in learning more about the C code that underpins R, so I'd be happy to take a look into this, once I've addressed #5, though I might not have a chance to do both on the day at Imperial.

**Comment by kbodwin** [comment]
@EllaKaye and I have submitted a patch that fixes the main issue of this bug, i.e., the misalignment of the divider.

The two other suggested changes in Bug 8934 are not addressed and could still be good Dev Day issues.

**Comment by hturner** [comment]
Patch is now in R-devel and bug has been marked as CLOSED FIXED :tada:

**Comment by EllaKaye** [comment]
When I'm back at work next week, I'll open another bugzilla report regarding the two additional suggested issues from the now closed one. Those are open to discussion, rather than genuine bugs, so good to treat them differently.

**Comment by mmaechler** [comment]
> When I'm back at work next week, I'll open another bugzilla report regarding the two additional suggested issues from the now closed one. Those are open to discussion, rather than genuine bugs, so good to treat them differently.

The  "do nothing for n=1" issue is indeed something to be discussed.  Remember Di Cook proposed the cutoff should even be, e.g., n <= 5 instead of n = 1.   Now bugzilla is really not the best place for discussions;  also it is only read by R-core members (+ Heather) generally, plus the PR "subscribers" specifically.  Usually I'd use the R-devel mailing list for discussing possible R changes. .. but you could open issues somewhere else and post / blog / chat / .. about it.

And the second issue brought up, the default `scale`, may be  "interesting", but then `stem()` is not really the most important R function, but rather almost a historical monument, no?

**Comment by EllaKaye** [comment]
Thanks @mmaechler for advising on the best forum for the discussion. Next week I'll raise this on the R-devel maillist, and possibly a Mastodon chat too.

**Comment by pmur002** [comment]
Thanks to Ella and Kelly for the fix!  Nice to see the regression test included in the patch too :)
